### ISSUE TITLE
tar_perams_ranged not working

### ISSUE THREAD

**Issue by maowerner** [chelmes/SoBERH#10]
In the last commits the argparse package was replaced by `import argument_parsing as ap`

What do I need to install to get `argument_parsing`?

**Comment by kostrzewa** [comment]
Nothing as far as I can tell, the argument parser has been simply extracted into a separate file. See Christopher's commit: https://github.com/chelmes/SoBERH/commit/164fdf685186961c151023494a3295ce29caee80#diff-a69c8601726bbbeff16217e50ca00d91

**Comment by maowerner** [comment]
Sorry, the error was how I called the script.
